import "server-only";
import { Document, Page, StyleSheet, Text, View, renderToBuffer } from "@react-pdf/renderer";
import { formatPKR } from "@/lib/money/paisa";

export interface InvoicePdfData {
  agency: { name: string; address: string | null; phone: string | null; email: string | null; taxNo: string | null };
  invoiceNumber: string;
  bookingNumber: string | null;
  customerName: string | null;
  amountPaisa: bigint;
  status: string;
  issuedAt: Date;
  notes: string | null;
}

const styles = StyleSheet.create({
  page: { padding: 42, fontFamily: "Helvetica", fontSize: 10, color: "#1f2937" },
  row: { flexDirection: "row", justifyContent: "space-between" },
  title: { fontSize: 24, fontFamily: "Helvetica-Bold" },
  agency: { fontSize: 18, fontFamily: "Helvetica-Bold" },
  muted: { color: "#6b7280", marginTop: 3 },
  box: { marginTop: 28, padding: 16, backgroundColor: "#f3f4f6" },
  amount: { marginTop: 28, paddingTop: 14, borderTopWidth: 1, fontSize: 18, fontFamily: "Helvetica-Bold", textAlign: "right" },
  notes: { marginTop: 28 },
  footer: { position: "absolute", bottom: 28, left: 42, right: 42, textAlign: "center", color: "#9ca3af", fontSize: 8 },
});

function InvoiceDocument({ data }: { data: InvoicePdfData }) {
  return (
    <Document title={`Invoice ${data.invoiceNumber}`}>
      <Page size="A4" style={styles.page}>
        <View style={styles.row}>
          <View>
            <Text style={styles.agency}>{data.agency.name}</Text>
            {data.agency.address ? <Text style={styles.muted}>{data.agency.address}</Text> : null}
            {data.agency.phone ? <Text style={styles.muted}>{data.agency.phone}</Text> : null}
            {data.agency.email ? <Text style={styles.muted}>{data.agency.email}</Text> : null}
            {data.agency.taxNo ? <Text style={styles.muted}>NTN: {data.agency.taxNo}</Text> : null}
          </View>
          <View>
            <Text style={styles.title}>INVOICE</Text>
            <Text style={styles.muted}>{data.invoiceNumber}</Text>
            <Text style={styles.muted}>{data.issuedAt.toISOString().slice(0, 10)}</Text>
          </View>
        </View>
        <View style={styles.box}>
          <Text>Customer: {data.customerName ?? "—"}</Text>
          <Text style={styles.muted}>Booking: {data.bookingNumber ?? "—"}</Text>
          <Text style={styles.muted}>Status: {data.status}</Text>
        </View>
        <Text style={styles.amount}>Total: {formatPKR(data.amountPaisa)}</Text>
        {data.notes ? <View style={styles.notes}><Text>Notes</Text><Text style={styles.muted}>{data.notes}</Text></View> : null}
        <Text style={styles.footer}>{data.agency.name} · Generated by Safar CRM</Text>
      </Page>
    </Document>
  );
}

export function renderInvoicePdf(data: InvoicePdfData): Promise<Buffer> {
  return renderToBuffer(<InvoiceDocument data={data} />);
}
